# Generated by Django 4.1 on 2022-08-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_doctor_biography_patient_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
