# Generated by Django 4.1 on 2022-09-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_test_active_test_created_at_test_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=25, null=True),
        ),
    ]
